Laboratorium 2/Models/Birth.cs
namespace Laboratorium_2.Models
{
    public class Birth
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public DateTime? Date { get; set; }

        public bool IsValid()
        {         
            if(CalculateDate() && Name is not null && Date.Value < DateTime.Now) 
            { 
                return true; 
            }
            return false;
        }

        private bool CalculateDate()
        {
            if (Date is not null)
            {
                Age = DateTime.Now.Year - Date.Value.Year;
                return true;
            }  
            else
            {
                return false;
            }
        }

        public string ToString()
        {
            string result = $"Cześć {Name}, masz {Age} lat(a)";
            return result;
        }
    }
}

Laboratorium 2/Models/Calculator.cs
namespace Laboratorium_2.Models
{
    public class Calculator
    {
        public string op { get; set; }
        public double? dig1 { get; set; }
        public double? dig2 { get; set; }

        public double Calculate()
        {
            double result = 0;
            switch (op)
            {
                case "add":
                    result = (double)(dig1 + dig2);
                    break;
                case "sub":
                    result = (double)(dig1 - dig2);
                    break;
                case "mul":
                    result = (double)(dig1 * dig2);
                    break;
                case "div":
                    result = (double)(dig1 / dig2);
                    break;
            }
            return result;
        }
        public bool IsValid()
        {
            if (op is null || (dig1 == 0 && dig2 == 0))
            {
                return false;
            }
            return true;
        }
    }
}

Laboratorium 2/Models/ErrorViewModel.cs
namespace Laboratorium_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorium 2/Models/Operators.cs
namespace Laboratorium_2.Models
{
    public enum Operators
    { 
        Add, Sub, Mul, Div
    }
}

Laboratorium 2/Controllers/BirthController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium_2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult FormBirth()
        {
            return View();
        }
        public IActionResult Hello(Birth model)
        {
            if (model.IsValid())
            {
                return View(model);
            }
            else
            {
                return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
        }
    }
}

Laboratorium 2/Controllers/CalculatorController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View();
        }
        public IActionResult Result(Calculator model)
        {
            if(model.IsValid())
            {
                return View(model);
            }
            else
            {
                return View();
            }
        }
    }
}

Laboratorium 2/Controllers/HomeController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Laboratorium 2/Views/Birth/FormBirth.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form action="Hello" method="post">
    <input type="text" name="Name"/><br/>
    <input type="date" name="Date"/><br/>
    <button type="submit">Wyślij Dane</button>
</form>

Laboratorium 2/Views/Birth/Hello.cshtml
@model Birth
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h3>@Model.ToString()</h3>

Laboratorium 2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form action="Result" method="get">
    <input type="number" name="dig1" step="0.0001"/><br/>
    <select name="op">
        <option value="add">Dodawanie</option>
        <option value="sub">Odejmowanie</option>
        <option value="mul">Mnożenie</option>
        <option value="div">Dzielenie</option>
    </select><br/>
    <input type="number" name="dig2" step="0.0001"/><br/>
    <button type="submit">Oblicz</button>
</form>

Laboratorium 2/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>Wynik działania na liczbach @Model.dig1 oraz @Model.dig2 to: @Model.Calculate()</h3>

Laboratorium 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="FormBirth">Birth</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>